version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 12
        commands:
            - node -v
            - apt-get install yarn
            - yarn install
    pre_build:
        commands:
            - echo Nothing to do in the pre_build phase...
    build:
        commands:
            - yarn build
    post_build:
        commands:
            - yarn test
cache:
    paths:
        - 'node_modules/**/*'